export const userTable = [
  {
    UserName: "Ankita",
    Type: "user",
    PublicAddress: "lkdje6t76gvhg",
    MobileNo: "9776553668",
    Gender: "Female",
    EmailId: "mailto:adj@kjhdygu.com",
    Country: "India",
    isVerified: "true",
  },
  {
    UserName: "GaganDeep",
    Type: "validator",
    PublicAddress: "lkdffje6t76gvhg",
    MobileNo: "9776553868",
    Gender: "Female",
    EmailId: "mailto:ggg@kjhdygu.com",
    Country: "Australia",
    isVerified: "false",
  },
  {
    UserName: "Jatinder",
    Type: "user",
    PublicAddress: "lkdje6t76gvhg",
    MobileNo: "97768653668",
    Gender: "Male",
    EmailId: "mailto:jtd@kjhdygu.com",
    Country: "Canada",
    isVerified: "true",
  },
  {
    UserName: "Ankita",
    Type: "user",
    PublicAddress: "lkdje6t76gvhg",
    MobileNo: "9776553668",
    Gender: "Female",
    EmailId: "mailto:adj@kjhdygu.com",
    Country: "India",
    isVerified: "false",
  },
  {
    UserName: "GaganDeep",
    Type: "validator",
    PublicAddress: "lkdffje6t76gvhg",
    MobileNo: "9776553868",
    Gender: "Female",
    EmailId: "mailto:ggg@kjhdygu.com",
    Country: "Australia",
    isVerified: "true",
  },
  {
    UserName: "Jatinder",
    Type: "validator",
    PublicAddress: "lkdje6t76gvhg",
    MobileNo: "97768653668",
    Gender: "Male",
    EmailId: "mailto:jtd@kjhdygu.com",
    Country: "Canada",
    isVerified: "false",
  },
];